Revert "fix prettier"
This reverts commit e5ba60dec6c4adb0e62dd5895f2371e2452eb6a8.

diff --git a/prettier/justfile b/prettier/justfile
--- a/prettier/justfile
+++ b/prettier/justfile
@@ -1,1 +1,32 @@
-{{ snippet "justfile.snippet" }}
+set shell := ["bash", "-uec"]
+
+shell_files := `find . -name .git -prune -o -name '*.sh' -print`
+
+[group('maint')]
+default:
+    @just --list
+
+[group('maint')]
+pre-commit: check-git-status
+    pre-commit sample-config >.pre-commit-config.yaml
+    pre-commit install --config .pre-commit-config.yaml
+    git add .pre-commit-config.yaml
+    pre-commit run --all-files
+
+# Checks if the git working directory is clean
+check-git-status:
+    #!/usr/bin/env bash
+    git status --porcelain || exit 0
+    echo "Error: Git working directory is not clean. Please commit or stash your changes first."
+    exit 1
+
+[group('maint')]
+fmt:
+    test -z "{{ shell_files }}" || shfmt -w -s -i 4 {{ shell_files }}
+    terraform fmt -recursive .
+    prettier --ignore-path=.prettierignore --config=.prettierrc.json --write .
+    just --unstable --fmt
+
+[group('lint')]
+lint:
+    test -z "{{ shell_files }}" || shellcheck {{ shell_files }}
